### ISSUE TITLE
【改进建议】支持mermaid版本能否持续更新

### ISSUE THREAD

**Issue by Multipleriver** [purocean/yank-note-extension#21]
## 【改进建议】支持mermaid版本能否持续更新

貌似mermaid扩展不能够支持新的语法，请问可以解决一下嘛，谢谢！
![image](https://github.com/purocean/yank-note-extension/assets/97719454/1f7d2a12-22f1-460b-967f-53f1b3bca988)

上图借用的示例代码来自https://mermaid.nodejs.cn/syntax/timeline.html
![image](https://github.com/purocean/yank-note-extension/assets/97719454/8d517ce4-47f1-4afe-8bb5-c228475cc539)

**Comment by purocean** [comment]
之前 Mermaid 升级 9.3 后有些不稳定，所以很久以来没更新。不过目前测试没什么问题了，已升级 Mermaid 至 10.6.0。可以安装新版本扩展 1.6.0 试试

**Comment by Multipleriver** [comment]
谢谢，已经尝试成功，感谢大佬！
