### ISSUE TITLE
【拓展建议】能否有个一键上传markdown文件插入的本地图片

### ISSUE THREAD

**Issue by Micking-M** [purocean/yank-note-extension#6]
与一键下载外链图片对应，有时（手机上看md文件通常外链图片能更好渲染出来）不得不将图片上传至图床，希望能有所支持

**Comment by purocean** [comment]
![image](https://user-images.githubusercontent.com/7115690/171213334-5494dde3-717e-438a-91fb-e6be8494ff96.png)
右键看看

以后要让这类功能更明显
